import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Oswald } from 'next/font/google';
import React from 'react';
import './globals.css';
import Header, { SocialMediasEnum } from '@/containers/Header/Header';
import Nav from '@/containers/Nav/Nav';

config.autoAddCss = false;

const oswald = Oswald({ subsets: ['latin'] });

export const metadata = {
  title: 'ORPM Spectacle - Les Misérables',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <div className="w-full">
          <Header socialMediasIcons={
            [SocialMediasEnum.FACEBOOK,
              SocialMediasEnum.FACEBOOK,
              SocialMediasEnum.INSTAGRAM,
            ]
          }
          />
          <Nav />
          <main className="max-w-content mx-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
